@startuml
'https://plantuml.com/class-diagram


class ex43Sol{
    Scanner kb
    $siteName
    $author
    $js
    $css

}
ex43<|-- WebsiteGenerator
class WebsiteGenerator
{
+boolean mkdir(String path)
+boolean createIndex(String site, String author) throws IOException
}


@enduml