@startuml
'https://plantuml.com/class-diagram
class Inventory{
+readJSONInfo(String path) : void

}
class Products
{
- Field: String name
- Field: double price
- Field: int quantity
+ getName(): String
+setName(String name) : void
+getQuantity: int
+setQuantity(int quantity): void
+getPrice: double
+setPrice(double price): void
}


@enduml